image: alpine

pages:
  script:
  - cd docs
  - apk add --no-cache python3 python3-tkinter
  - pip3 install sphinx sphinxcontrib-napoleon sphinx_rtd_theme
  - apk --no-cache add make
  - make html
  - mv _build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
