image: alpine

pages:
  script:
  - cd docs
  - apk add --no-cache python3
  - pip3 install sphinx sphinxcontrib-napoleon
  - apk --no-cache add make
  - make html
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
